### ISSUE TITLE
Glykerol density is incorrect and volume is undefined

### ISSUE THREAD

**Issue by LouisB3** [JPLRepo/DeepFreeze#100]
@JPLRepo. [Cross-posting here from the forums for visibility](https://forum.kerbalspaceprogram.com/index.php?/topic/112328-110x-deepfreeze-v0290-17th-oct-2020/&do=findComment&comment=3896511). 

Per earlier comments made by scottpaladin, Glykerol is supposed to be a 1L/unit resource with a density similar to glycerol. However, the volume of the Glykerol was never defined in CRP's resource definition; more importantly, density is 10x higher than intended due to a typo. 

I recommend changing the resource definition as follows and would be happy to submit a PR to CRP with your approval:

```
RESOURCE_DEFINITION
{
   name = Glykerol
   displayName = #LOC_CRP_Glykerol_DisplayName
   density = 0.001261 // same as glycerol
   unitCost = 2
   hsp = 2430 // specific heat capacity (kJ/tonne-K as units) // http://www.engineeringtoolbox.com/specific-heat-fluids-d_151.html
   flowMode = ALL_VESSEL
   transfer = PUMP
   isTweakable = true
   volume = 1
   ksparpicon = REPOSoftTech/DeepFreeze/Icons/Glykerol
   ksparpdisplayvalueas = Units
}
```

These changes won't affect much in DeepFreeze by itself, since most vessels probably only carry a few liters of Glykerol. But it's important to specify these values for interoperability with other mods, so they can add tank options and/or ISRU conversions where desired.

**Comment by JPLRepo** [comment]
PR submitted to CRP to update this.
https://github.com/BobPalmer/CommunityResourcePack/pull/257

**Comment by LouisB3** [comment]
I'll close this since the associated PR has been merged. Thanks!
