### ISSUE TITLE
DeepFreeze does not support saving and loading without BackgroundResources installed

### ISSUE THREAD

**Issue by marr75** [JPLRepo/DeepFreeze#106]
BackgroundResources is not listed as a required dependency but DeepFreeze is compiled against and imports it directly in several critical classes. In practice, this results in a FileNotFound exception (namely, the BR dll) in operations relating to saving and loading the DeepFreeze scenario node of the save file. The node ends up with no known vessels and no known parts and so, upon loading, your frozen Kerbals are no longer associated with the vessel they were frozen on.

To replicate:
- Install DeepFreeze
- Make sure BackgroundResources is not installed
- Launch any game where you have access to a freezer part
- Load the part with a kerbal
- Freeze the kerbal
- Save the game
- Load the game
- Your frozen kerbal will be disassociated from the vessel and part, they can be thawed from the space center but cannot be thawed in the vessel or part they were frozen in

You can see a [player log file](https://www.dropbox.com/s/kv8wu1cyg2ehcoh/KSP.log?dl=0) from an example of this as provided by DOOM89 on the forum.

**Comment by JPLRepo** [comment]
Background Resources is part of Deepfreeze and required for it to run. It's distributed with Deepfreeze.
Don't remove it.
