### ISSUE TITLE
EC Drains exponentially after time warp

### ISSUE THREAD

**Issue by joshsellers** [JPLRepo/DeepFreeze#109]
[Video](https://imgur.com/a/9wkftCu)
[Player.log and craft file](https://drive.google.com/drive/folders/1oUcMQRlfxxwMJsAqEQQPkYq4G9RWQWN-?usp=sharing)

**Comment by JPLRepo** [comment]
You don't have backgroundresources in your install. This is a critical DLL required for deepfreeze to function.
It is distributed with the zip file i supply for this mod. If you install the zip file into your game as per the instructions on the forum you will have no issues.
