### ISSUE TITLE
Black screen and the game breaks to change ships .

### ISSUE THREAD

**Issue by Rikaius** [JPLRepo/DeepFreeze#26]
By using the cabin size 2.5 in orbit, changing ship screen turns black and if I select a grounded ship the floor is not displayed and kerbals not displayed and the game becomes unplayable having to close using Alt + f4 in both cases.

Do not know if this mod some ocacionados this, but I send a picture with the mods I have.

Use google translator that not English : 3

![123](https://cloud.githubusercontent.com/assets/14846607/10115997/0d25dd1a-63e5-11e5-99cb-7be95cc30fe7.PNG)

**Comment by JPLRepo** [comment]
For help I need logs. 
Please follow the [support instructions here](http://forum.kerbalspaceprogram.com/threads/92229-How-To-Get-Support-%28READ-FIRST%29). I need the detailed output Logs as per bullet 1 about halfway down the page. NOT the Ksp.log. It would also help if you go into DeepFreeze settings at the KSC and turn Debugging option ON before replicating the error and capturing the logs (yes this will create lag while you do it, but the extra log info it writes will help).

**Comment by JPLRepo** [comment]
Try Version 0.19.0.0 of DeepFreeze Continued... and advise if you still have issues.
If you still have problem please follow the support instructions link above and send/post your KSP logs.

**Comment by JPLRepo** [comment]
No response. No other reports of problem. Closing issue.
