### ISSUE TITLE
automatic opening after a specific time

### ISSUE THREAD

**Issue by Joshwoo69** [JPLRepo/DeepFreeze#35]
like after a certain time eg 1 year, the cryopods open and the crew is un thawed.

**Comment by JPLRepo** [comment]
This can be achieved as-is if you have Kerbal Alarm Clock installed.
Simply create a KAC alarm for the time you want, go into DeepFreeze GUI and click "Alarms" button.
Modify the alarm you created to include thaw events for each kerbal. Done.
