### ISSUE TITLE
CRY-0300 (disconnected at front/top node, BUT STILL CONNECTED!)

### ISSUE THREAD

**Issue by RB1O1** [JPLRepo/DeepFreeze#37]
upon constructing a craft with this part in, whenever I launch the craft the part simply isn't connected at the front(SPH) or top(VAB) node, any part connected to it simply fall to the ground. BUT these parts are not disconnected, even though they are physically connected they still count as a single craft to the game. I have no idea what is causing this but it isn't fun this needs addressing, I've un-installed all mods leaving only Deepfreeze continued and this is still prevalent. 

![screenshot5](https://cloud.githubusercontent.com/assets/16658627/12253035/a00afd74-b8d4-11e5-8f6f-f5e1a05c39ea.png)
![screenshot6](https://cloud.githubusercontent.com/assets/16658627/12253037/a2524664-b8d4-11e5-82ba-2de09740c66b.png)

**Comment by JPLRepo** [comment]
Interesting... But I cannot replicate your error. Works fine for me.
Please supply log files as I think something else is going on here.
No log = no support - sorry.

**Comment by kushmann2** [comment]
I am having the same issue, sometimes it'll just load a weird setting when you go to launch, Ill upload pics and a log.

**Comment by kushmann2** [comment]
![screenshot0](https://cloud.githubusercontent.com/assets/16738293/12375198/eb8f1446-bc7c-11e5-96fe-3bc4b72e0abd.png)
![screenshot1](https://cloud.githubusercontent.com/assets/16738293/12375200/f185072a-bc7c-11e5-81ee-e972693eda98.png)

**Comment by kushmann2** [comment]
![screenshot2](https://cloud.githubusercontent.com/assets/16738293/12375202/01d2824c-bc7d-11e5-877f-2cb74cf4721d.png)

**Comment by kushmann2** [comment]
[output_log.txt](https://github.com/JPLRepo/DeepFreeze/files/93154/output_log.txt)

**Comment by JPLRepo** [comment]
Thanks for the log. I had a quick look a few days ago, and I did manage to get errors when I launch a vessel with a CRY-0300 and revert to the VAB and then re-launch. But I didn't get exactly the same as you have reported above. I will continue to investigate.

**Comment by JPLRepo** [comment]
I might have a fix... not sure... because I am unable to replicate the error myself. Can you try [this dev version](https://github.com/JPLRepo/DeepFreeze/blob/dev/DeepFreeze.zip) and report back please.

**Comment by kushmann2** [comment]
So far so good! I'll report anymore bugs I find. Thank you so much!

**Comment by JPLRepo** [comment]
Fixed.
