### ISSUE TITLE
CKAN Homepage is out of date

### ISSUE THREAD

**Issue by Guard13007** [JPLRepo/DeepFreeze#49]
The link provided on CKAN for this mod leads to a 404 page instead of the forum thread.

It gives `http://forum.kerbalspaceprogram.com/index.php?/topic/112328`

When it should be `http://forum.kerbalspaceprogram.com/threads/124720`

**Comment by JPLRepo** [comment]
I don't support CKAN. Closing.

**Comment by Guard13007** [comment]
I will notify them instead then, thank you.

**Comment by Guard13007** [comment]
Actually, it's your [SpaceDock page](http://spacedock.info/mod/142/DeepFreeze%20Continued...) that is out of date. Same issue.

**Comment by JPLRepo** [comment]
I am not following you. The "Mod Website" link on my SpaceDock page is correct and points here:
http://forum.kerbalspaceprogram.com/index.php?/topic/112328-11-deepfreeze-continued
which when I open in my browser goes to my forum thread for this mod.

**Comment by Guard13007** [comment]
Okay, the issue has resolved itself. It was a caching issue that hadn't propagated from your fixes and/or the forum not properly redirecting the links to the actual page.

The CKAN is automatically updating its info from SpaceDock, and all of that is handled for you. I misunderstood how your mod was in the system, and I apologize for bothering you about it.
