### ISSUE TITLE
Settings Tooltip Background Color

### ISSUE THREAD

**Issue by deimos790** [JPLRepo/DeepFreeze#51]
From here:
http://forum.kerbalspaceprogram.com/index.php?/topic/112328-111-deepfreeze-continuedksp-112-update-v0221-1st-may-2016/&do=findComment&comment=2553439

DeepFreeze ToolTip Background is hard to read in contrast to the tooltip text when compared to AmpYear, even though the two mods apparently use identical tooltip background icons.

**Comment by JPLRepo** [comment]
Ok there must be something going in with your install. Because the tooltips look great and the same as AmpYear for me in DeepFreeze. Can you send me your log?

**Comment by JPLRepo** [comment]
Bug related to folder names on Linux platform. Fixed for next release.
