### ISSUE TITLE
wrong mass CRY-300

### ISSUE THREAD

**Issue by wigge1** [JPLRepo/DeepFreeze#59]
Noticed that the mass in the config files are the same for CRY-1300 and CRY-300.
2.5 tons each and it is obviously the CRY-300 that is faulty.

Thanks for maintaining the mod. :)

**Comment by JPLRepo** [comment]
?? Maintaining ?? I wrote it? Anyway.
Thanks.
Change to 1.5t for next version.

**Comment by wigge1** [comment]
Oh, I am sorry, got confused by the wording in the forum post for it. 
Many thanks for the great fun mod then :)
