### ISSUE TITLE
Settings/Status Dialogue Box Does not Display

### ISSUE THREAD

**Issue by caodwolf** [JPLRepo/DeepFreeze#61]
First off I just love this mod.  THe imangination of the moddlers out there just continue to amaze me and provides so much color into the game.sim.   I've been using Deep Freeze for sometime now but as of late when I click on the 'deepfreeze' icon in any view I just get a two-tone grey bar.   I've provided a screen snapshot of this.  I also attached the required output.log.   

The Deep Freeze functions still works fine,  I can freeze and unfreeze without any issues.   It's just the option/status screen no longer displays.   It was not always like this,  it's only recently this has occurred.   I downloaded a fresh ZIP, deleted  the existing file and reinstalled but to no avail.

This is not a big deal as the MOD still works fine.  I do miss tracking which Kerbals are in Deep Freeze and of course the options to play around with.

Appreciate any assistance.   I see there is an open issue which kind of pertains to this but there is no detail highlighted within this open ticket.

Dave T

caodwolf@gmail.com

[output_log.txt](https://github.com/JPLRepo/DeepFreeze/files/474778/output_log.txt)

![screenshot33](https://cloud.githubusercontent.com/assets/22218282/18552106/23cc707c-7b29-11e6-9bbc-70f577fab8a4.png)

**Comment by JPLRepo** [comment]
Looks like DeepFreeze is having issues finding a vessel by your log.
Can you also supply your save file (persistent.sfs) so I can try to determine where things have gone wrong.

**Comment by caodwolf** [comment]
JPLRepo-
Thanks for the response.   I've attached the persistent file (zipped).     I did lose a ways back a vessel whose lone crew member was hibernating via Deep Freeze.  I could never figure out what happened to that vessel and assumed there was some catastrophic event and it was lost.   That was so many missions ago that I forget the name of the vessel.  I just moved on....

Anyway,  appreciate your assistance.

Dave T 

[persistent.zip](https://github.com/JPLRepo/DeepFreeze/files/490446/persistent.zip)

**Comment by JPLRepo** [comment]
Yes there is two DeepFreeze Freezers defined in your save file but there is no record of the vessel they are meant to be part of anywhere in your save file.
If you remove these lines from your save file it should fix the problem.
Please let me know if it does, I'll make a change to the code to handle this a bit better in case it ever happens again (even though it isn't meant to).
```   
            PartInfo
			{
				vesselID = 84329983-173f-4fef-9de1-00b6767b5fe9
				PartName = CRY-0300RFreezer
				numSeats = 1
				numCrew = 1
				crewMembers = Landred Kerman
				crewMemberTraits = Scientist
				numFrznCrew = 0
				hibernating = False
				hasextDoor = False
				hasextPod = True
				timeLastElectricity = 34296856
				frznChargeRequired = 10
				timeLastTempCheck = 0
				deathCounter = 0
				tmpdeathCounter = 0
				outofEC = False
				TmpStatus = OK
				cabinTemp = 180.1697
				ECWarning = False
				TempWarning = False
				lastUpdate = 9998507.54669113
				flightID = 3294743639
			}
			PartInfo
			{
				vesselID = 84329983-173f-4fef-9de1-00b6767b5fe9
				PartName = CRY-0300RFreezer
				numSeats = 1
				numCrew = 0
				crewMembers = 
				crewMemberTraits = 
				numFrznCrew = 0
				hibernating = False
				hasextDoor = False
				hasextPod = True
				timeLastElectricity = 34296856
				frznChargeRequired = 10
				timeLastTempCheck = 0
				deathCounter = 0
				tmpdeathCounter = 0
				outofEC = False
				TmpStatus = OK
				cabinTemp = 180.1983
				ECWarning = False
				TempWarning = False
				lastUpdate = 9998507.54669113
				flightID = 2717673493
			}
```

**Comment by JPLRepo** [comment]
I have added a Database synchronization/cleanup on Save game load to deal with this in the future if it occurs.
