### ISSUE TITLE
Only show App Launcher button when parts on ship

### ISSUE THREAD

**Issue by Gribbleshnibit8** [JPLRepo/DeepFreeze#68]
The app launcher gets crowded. It'd be nice if it were possible to set the button to only show in Flight when there are valid parts on the vessel.

**Comment by JPLRepo** [comment]
Defeats the purpose... 
Because you may have frozen kerbals on other vessels that are not the active vessel.

**Comment by Gribbleshnibit8** [comment]
Then that vessel could be switched to, app launcher button appears because valid parts, manage Kerbals. Or go to Space Center to manage them from there. It's is weird to me to have it sitting there from day one on career saves where it will be several in-game years before I even unlock the parts.
