### ISSUE TITLE
IVA display vanishes when you are frozen.

### ISSUE THREAD

**Issue by Virindi-AC** [JPLRepo/DeepFreeze#76]
If you IVA to a kerbal then freeze them using the DeepFreeze menu, once the freeze is complete you are left with a glitched IVA.

http://www.virindi.net/junk/deepfreeze1.png

Repro steps:
1) Build a craft and crew it with a single kerbal inside a freeze pod. Here is the one I built to verify this:
http://www.virindi.net/junk/deepfreeze2.png
2) Launch and go IVA as your kerbal.
3) Open the DeepFreeze menu and click the "Freeze" button
4) Wait for the freeze to complete

Tested on a clean install KSP 1.2.2 Win64 with only required mods.

**Comment by JPLRepo** [comment]
The condition is just when there is a single kerbal on-board that gets frozen.
This is because stock destroys the internal when there are no kerbals on-board.
I haven't found a fix yet.
But next version will kick you out of IVA view if you freeze the last kerbal on board.
