### ISSUE TITLE
Kerbals in deep freeze disappearing

### ISSUE THREAD

**Issue by DrDoofTwitch** [JPLRepo/DeepFreeze#83]
Good day. I had an issue where I landed with 2 kerbals in deep freeze, the recovered the parts and the kerbals dissappeared as in completely.

**Comment by JPLRepo** [comment]
Without a log not a lot I can do about that.

**Comment by DrDoofTwitch** [comment]
No worries. It happened a little while ago (not sure exactly when), and when speaking to Linuxgurugamer he suggested I post a bug report about it. So I'm not sure when or where to find the log (because I don't remember exactly when it happened). Just thought I'd bring it to your attention.

In case it happens to someone else, or you feel like trying to reproduce it, here is what happened:

Kerbals in deep freeze (frozen still) were brought home to Kerbin. Craft was recovered (whilst still containing Kerbal popsicles). No Kerbals were recovered from the craft, Kerbals are not missing or on assignment, they are just gone.

Great mod. Thanks for the time you put into developing and maintaining it. *Cheers*
