### ISSUE TITLE
Pink Texture on Cryopods for IVA/Show Interior

### ISSUE THREAD

**Issue by EliteMaster512** [JPLRepo/DeepFreeze#87]
The following is a copy/paste of a post on the KSP Forums:

Hello, and thank you for making this wonderful mod! Now I can get to Duna without having to build a giant station with a living quarters, a greenhouse, and all of that. At least not yet anyways!

However when I use this mod, I get a shader/texture error on the pods in the form of a opaque pink color. Pictured here: https://cdn.discordapp.com/attachments/295199794102796288/546831963051393024/screenshot32.png

The pink hue appears in IVA, and when using the "Show Interior" option in the lower right-hand corner.

I will post a log below,  but as you can see I have many mods installed, so chances are its an incompatibility thing. Among the mods used are Planetshine, Kopernicus, and Scatterer. I'm using the Astronomer's Visual Pack with KSPRC textures.

Disabling Scatterer/Planetshine seems to do nothing. I am also using the JSI patch, not sure if that's applicable to IVA. Here is the log, which will naturally contain all mods used.

Log - https://drive.google.com/file/d/1uAxIySo6bbndrRAp5-GX41f6yud_aWDp/view?usp=sharing

I am still having this issue on the build for 1.6.x, v0.24.0.0.

I did manually uninstall the mod before reinstallation.

**Comment by EliteMaster512** [comment]
KSP Version is 1.6.1
[config] build id = 024012019.01.08 at 12:56:12 PST Branch: master language = en-us

**Comment by EliteMaster512** [comment]
The pods pictured were launched when the 1.5.1 build was installed. Will start the game up again and make a new craft to see if that helps.

System Info: https://drive.google.com/open?id=1jgHmmRu-7wjZRDBvqsPDYDnMpVucIGn_

**Comment by EliteMaster512** [comment]
When frozen, pods have a black texture.

https://i.gyazo.com/697c23cc0aa7b6a691aa88cfd962c49f.png

I've seen this bug reported previously, I hope I'm an isolated incident.

**Comment by GIToews** [comment]
I am having the same issue. I have a fresh 1.6.1 install going and only installed DeepFreeze and JSI ﻿Advanced Transparent Pods (downloaded from spacedock today)
[output_log.txt](https://github.com/JPLRepo/DeepFreeze/files/2933917/output_log.txt)

**Comment by JPLRepo** [comment]
This got fixed long time ago. Closing.
