### ISSUE TITLE
Right-Click Not Working

### ISSUE THREAD

**Issue by ghost** [JPLRepo/DeepFreeze#93]
I just installed DeepFreeze to complement the life support mod I have (Snacks), and there appears to be a problem with its parts. If I add a stock part to a new design, I can right click the part and adjust autostrut, EC, etc. (everything you usually can). But after I add a DeepFreeze part, when I right click any part, nothing happens.

I have restarted KSP, Steam, and even my computer multiple times, and I've "verified the integrity of game files" twice, to no avail.

[LOG](http://bit.ly/deepfreezelog)

**Comment by JPLRepo** [comment]
Sorry took so long to reply, this one completely slipped under my radar.
I see no errors related to DeepFreeze in the supplied log information.
Are you still experiencing issues with the latest version of KSP and DeepFreeze?
