### ISSUE TITLE
BackgroundRecourses: Dependency?

### ISSUE THREAD

**Issue by YpsilonTM** [JPLRepo/DeepFreeze#96]
Is backgroundResources really a Dependency or more a recommended mod. Because now it's not possible to install DeepFreeze and Kerbalism at the same time with CKAN. Because the BackgroundResources conflict with Kerbalsim

**Comment by JPLRepo** [comment]
I don't support CKAN so can't help you.
BackgroundResources is required to run DeepFreeze and should never removed from it's separate folder.
